In [1]:
import torch

In [7]:
import numpy as np

In [8]:
def soft(n):
    return np.exp(n)/np.sum(np.exp(n))

In [9]:
x = np.array([2,2.2,2.8,3,3.4,3.9,4,4.9])

In [11]:
output = soft(x)
output

array([0.02300462, 0.02809791, 0.05119773, 0.06253305, 0.09328835,
       0.15380649, 0.16998246, 0.41808938])

In [16]:
y = torch.tensor(x)
y

tensor([2.0000, 2.2000, 2.8000, 3.0000, 3.4000, 3.9000, 4.0000, 4.9000])

In [17]:
torch.softmax(y , dim=0)

tensor([0.0230, 0.0281, 0.0512, 0.0625, 0.0933, 0.1538, 0.1700, 0.4181])

In [18]:
torch.sigmoid(y)

tensor([0.8808, 0.9002, 0.9427, 0.9526, 0.9677, 0.9802, 0.9820, 0.9926])

In [19]:
torch.relu(y)

tensor([2.0000, 2.2000, 2.8000, 3.0000, 3.4000, 3.9000, 4.0000, 4.9000])

In [20]:
torch.tanh(y)

tensor([0.9640, 0.9757, 0.9926, 0.9951, 0.9978, 0.9992, 0.9993, 0.9999])