In [2]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [3]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [5]:
from sklearn.linear_model import LogisticRegression 
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier 


In [8]:
import numpy as np 


In [18]:
from sklearn.datasets import load_digits
digits = load_digits()

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test ,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [20]:
lr = LogisticRegression()
lr.fit(X_train ,y_train)
lr.score(X_test,y_test)

C:\Users\ADIT\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.975925925925926

In [21]:
svm = SVC()
svm.fit(X_train ,y_train)
svm.score(X_test,y_test)

0.9888888888888889

In [22]:
rf = RandomForestClassifier()
rf.fit(X_train ,y_train)
rf.score(X_test,y_test)

0.9851851851851852

In [23]:
def get_score(model,X_train,X_test ,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test , y_test)

In [25]:
get_score(SVC(),X_train,X_test , y_train,y_test)

0.9888888888888889

In [26]:
from sklearn.model_selection import StratifiedKFold

In [ ]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [45]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [39]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [40]:
scores_rf

[0.9148580968280468, 0.9565943238731218, 0.9265442404006677]

In [46]:
# cross_val_score function 
from sklearn.model_selection import cross_val_score


In [49]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target , cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [50]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target , cv=3)

array([0.93489149, 0.94991653, 0.93322204])

In [53]:
cross_val_score(SVC(gamma='auto'),digits.data,digits.target , cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [56]:
scores1=cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target , cv=3)
np.average(scores1)

0.9321090706733445

In [57]:
scores2=cross_val_score(RandomForestClassifier(n_estimators=20),digits.data,digits.target , cv=10)
np.average(scores2)


0.9376691495965238

In [58]:
scores3=cross_val_score(RandomForestClassifier(n_estimators=30),digits.data,digits.target , cv=10)
np.average(scores3)

0.9421260086902544

In [59]:
scores4=cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target , cv=10)
np.average(scores4)

0.9527032898820608